version: '3.8'

services:
  setup:
    image: alpine
    command: >
      sh -c "mkdir -p /data/bbssr_data /data/bbssr_db && 
             chown -R ${PID:-1000}:${GID:-1000} /data"
    volumes:
      - bbssr_data:/data/bbssr_data
      - bbssr_db:/data/bbssr_db

volumes:
  bbssr_data:
    name: bbssr_data
  bbssr_db:
    name: bbssr_db 