# External volumes configuration for production deployments
# This creates named volumes that persist data across container restarts

version: '3.8'

volumes:
  bbssr_data:
    name: ${DATA_VOLUME_NAME:-bbssr_data}
    external: true
  bbssr_db:
    name: ${MONGODB_VOLUME_NAME:-bbssr_db}
    external: true