version: '3.8'

name: ${STACK_NAME:-bbssr}

networks:
  app_network:
    name: ${STACK_NAME:-bbssr}_app_network
    driver: bridge
  db_network:
    name: ${STACK_NAME:-bbssr}_db_network
    driver: bridge

x-postgres-condition: &postgres-condition
  condition: service_healthy
  required: false

services:
  web:
    container_name: ${STACK_NAME:-bbssr}_web
    build: .
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - ${STACK_NAME:-bbssr}_backblaze_data:/data
    user: "appuser"
    restart: unless-stopped
    networks:
      - app_network
      - db_network
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres: *postgres-condition
      
  cloudflared:
    container_name: ${STACK_NAME:-bbssr}_cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - stack.env
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy
        
  postgres:
    container_name: ${STACK_NAME:-bbssr}_postgres
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ${STACK_NAME:-bbssr}_postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bbssr_user} -d ${POSTGRES_DB:-bbssr_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      # Service will only start if USE_POSTGRES=true
      replicas: ${USE_POSTGRES:-0}

volumes:
  ${STACK_NAME:-bbssr}_backblaze_data: {}
  ${STACK_NAME:-bbssr}_postgres_data: {}
