version: '3.8'

volumes:
  bbssr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/bbssr_data
  bbssr_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/bbssr_db 