version: '3.8'

services:
  setup:
    image: alpine
    command: >
      sh -c "mkdir -p /data/bbssr_data && 
             chown -R ${PID:-1000}:${GID:-1000} /data"
    volumes:
      - bbssr_data:/data/bbssr_data

  web:
    image: bbssr
    container_name: ${STACK_NAME:-bbssr}_web
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - bbssr_data:/data
    user: "${PID:-1000}:${GID:-1000}"
    restart: unless-stopped
    networks:
      - app_network
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${STACK_NAME:-bbssr}_cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - stack.env
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy

networks:
  app_network:
    name: ${STACK_NAME:-bbssr}_app_network
    driver: bridge

volumes:
  bbssr_data:
    name: bbssr_data 