# This Docker Compose file is for testing the fixed S3 API integration

version: '3'

services:
  bbssr-web:
    build: .
    container_name: bbssr-web-test
    volumes:
      - ./app:/app/app
      - ./data:/data
    ports:
      - "5001:5000"  # Map to a different port to not conflict with existing deployments
    environment:
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - DATABASE_URI=sqlite:////data/backblaze_snapshots.db
      - USE_S3_API=True
      - USE_ACCURATE_BUCKET_SIZE=True
      - DEBUG=True
    restart: unless-stopped
